/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[]) {
		System.out.println("Make comment here.");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
